# HTTPS
server:
  ssl:
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12

# MySQL
spring:
  datasource:
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# JWT
token:
  secret-key: ${TOKEN_SECRET_KEY}
  access-token-expiration-minutes: ${TOKEN_ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-days: ${TOKEN_REFRESH_TOKEN_EXPIRATION_DAYS}

# Image Upload S3
cloud:
  aws:
    region: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_CREDENTIALS_ACCESS_KEY}
      secretKey: ${AWS_CREDENTIALS_SECRET_KEY}
    s3:
      bucketName: ${AWS_S3_BUCKET_NAME}
