# HTTPS
server:
  ssl:
    key-store: # classpath:ssl/keystore.p12
    key-store-password:
    key-store-type: PKCS12

# MySQL
spring:
  datasource:
    url: # jdbc:mysql://{HOST}:{PORT}/{DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# Redis
  data:
    redis:
      host:
      port:

# Gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:

# OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - profile
              - email

          kakao:
            client-id:
            client-secret:
            redirect-uri:
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT
token:
  secret-key:
  access-token-expiration-minutes:
  refresh-token-expiration-minutes:

# AWS
cloud:
  aws:
    region:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucketName:

# application-local.yml
    dynamodb:
      endpoint:

# PortOne
port-one:
  api-key:
  api-secret:
