server:
  port: 80

spring:
  application:
    name: for-dogs
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true

springdoc:
  use-fqn: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  version: 0.1
  swagger-ui:
    path: /docs
    defaultModelsExpandDepth: 3
    default-model-expand-depth: 3
