server:
  domain: api.fordogs.store
  port: 443

service:
  domain: fordogs.store

spring:
  application:
    name: for-dogs
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
      resolve-lazily: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  batch:
    job:
      enabled: true

springdoc:
  use-fqn: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  version: 0.1
  swagger-ui:
    path: /docs
    defaultModelsExpandDepth: 3
    default-model-expand-depth: 3
