spring:
  datasource:
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

token:
  secret-key: ${TOKEN_SECRET_KEY}
