# HTTPS
server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password:
    key-store-type: PKCS12

# MySQL
spring:
  datasource:
    url: # jdbc:mysql://{HOST}:{PORT}/{DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# Redis
  data:
    redis:
      host:
      port:

# JWT
token:
  secret-key:
  access-token-expiration-minutes:
  refresh-token-expiration-days:

# AWS
cloud:
  aws:
    region:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucketName:

# application-local.yml
    dynamodb:
      endpoint:

# PortOne
port-one:
  api-key:
  api-secret:
